#端口号限制：8081、8082、8083等808开头表示同一个服务的集群
spring:
  application:
    # 服务名称
    name: spring-cloud-alibaba-nacos-register-demo
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 192.168.134.100:8848
server:
  port: 8012