spring:
  application:
    # 服务名称
    name: spring-cloud-alibaba-nacos-discovery-demo
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 192.168.134.100:8848
server:
  port: 8021

feign:
  hystrix:
    #hystix功能开启，失败降级
    enabled: true